language: go
go:
  - 1.10.x
before_install:
  - go get golang.org/x/tools/cmd/cover github.com/golang/lint/golint
  - >
    ver=1.4.5 &&
    wget -nv http://www.apache.org/dist/hbase/$ver/hbase-$ver-bin.tar.gz &&
    echo "1C34A448DF4E102E7964C6D884C2B1E535DD0CAAE67E6B1592DB2B108A6D3A0FB2D841F7677EB5C38EB6D78F342CB42F8CE90AA6D62A53623C7270234E8C95EE  hbase-$ver-bin.tar.gz" | sha512sum --strict --check - &&
    tar zxf hbase-$ver-bin.tar.gz --exclude=docs &&
    ln -s hbase-$ver hbase
install:
  - ./install_ci.sh
after_success:
  - make coverdata
  - bash <(curl -s https://codecov.io/bash)
before_script:
  - hbase/bin/hbase-daemon.sh --config hbase/conf start master
script:
  - make -j4 jenkins GOTEST_FLAGS=-v
